name: example_gallery
description: Hosted web gallery for dnd_kit example demos.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  basic_drag_drop:
    path: ../basic_drag_drop
  flutter:
    sdk: flutter
  kanban_board:
    path: ../kanban_board
  multi_container_sortable:
    path: ../multi_container_sortable

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
